### ISSUE TITLE
Cocoapods Integration failing From V1.3.5 to V1.3.6

### ISSUE THREAD

**Issue by sharanbasappa95** [razorpay/razorpay-pod#200]
<img width="1011" alt="image" src="https://github.com/razorpay/razorpay-pod/assets/61407045/83d0eca8-9ea2-47c8-b64f-341a8c43ac13">

In Github Actions, I am able to see it the cocoa pods deployment getting failed. We are not able to update to latest version of razor pay sdk of V1.3.5 & 1.3.6

**Comment by SuryakantRapido** [comment]
when we are publishing update V1.3.5 by cocoapod ?

**Comment by vivekshindhe** [comment]
Not sure what the issue is but v1.3.6 is already available on cocoapods [here](https://cocoapods.org/pods/razorpay-pod). Also attaching an image of pod install

<img width="558" alt="Screenshot 2024-02-08 at 4 40 12 PM" src="https://github.com/razorpay/razorpay-pod/assets/57621906/ba11176f-7ec3-4bd0-b121-4e03809c5ddf">

**Comment by sharanbasappa95** [comment]
@vivekshindhe GitHub action is failed for V1.3.6 for cocoa pods release, Please have a look on the action failures. 
https://github.com/razorpay/razorpay-pod/actions/runs/7724715165

**Comment by vivekshindhe** [comment]
Github Action has failed, so we pushed it to cocoapods manually.  To update to latest version use can use 
`pod update razorpay-pod`

**Comment by harrymash2006** [comment]
@vivekshindhe we are getting this error: `the id provided does not exist` when we try the payment with valid order_id and valid key. This happens in latest 1.3.6 version. the payment flow was working fine in `1.2.5.`.

Note: We are using test mode.
