### ISSUE TITLE
how to remove x86_64 , i386 from Razorpay.framework?

### ISSUE THREAD

**Issue by vuevrn** [razorpay/razorpay-pod#4]
Please check this issue

https://github.com/razorpay/razorpay-ios-sample-app/issues/7

**Comment by AbhinavArora95** [comment]
When a framework is distributed, it contains architectures of the simulators so that the consumer of the framework can build it on a simulator. However, when you are uploading the archive on itunes, you have to strip these architectures. If you would have been using cocoapods, it would have been done by it. Since, probably you are not using it, please run the attached script on the Razorpay.framework within your archive or before create the archive. 
[StripInvalidArchitectures.txt](https://github.com/razorpay/razorpay-pod/files/1867789/StripInvalidArchitectures.txt)

**Comment by vuevrn** [comment]
After following what you just said, it all works fine in other devices, only on iPhone 5-5s devices - it crashes. How do I solve in iPhone 5-5s devices? that's the issue. Please help me through this. 

thank you!

**Comment by vuevrn** [comment]
![screen shot 2018-04-02 at 3 48 34 pm](https://user-images.githubusercontent.com/10462847/38193105-e470e3fa-368d-11e8-8a83-74d21b062321.png)

please check the screenshot

**Comment by AbhinavArora95** [comment]
Can you please drop an email at support@razorpay.com with your crash log and the integration code.
